apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tsduck.fullname" . }}-config
  labels:
    {{- include "tsduck.labels" . | nindent 4 }}  
data:
  {{ .Values.autorun | toYaml | nindent 4 }}
