apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tsduck.fullname" . }}-secret
  labels:
    {{- include "tsduck.labels" . | nindent 4 }}  
data:
  {{- range $key, $val := .Values.env.secret }}
    {{- if $val}}
  {{ $key }}: {{ $val | b64enc }}
    {{- end}}
  {{- end}}