name: Build and publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: rabbitlabs/tsduck
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ secrets.PUBLISH_TOKEN }} 
        charts_dir: tsduck       